# -*- coding: utf-8 -*-
"""Thesis_XLNet Main Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SOsn1YDJMEgMPlFWpYavzsNnT3emSNfR
"""

from google.colab import drive
drive.mount('/content/drive')

"""**1. Set Up Environment**"""

!pip install transformers torch datasets scikit-learn pandas

"""**2. Import Data**"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from datasets import Dataset
import torch
from transformers import XLNetTokenizer, XLNetForSequenceClassification, Trainer, TrainingArguments
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

# Load dataset
data_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/EN_train.csv')

"""**3. Data Pre-processing**"""

# Handle missing values
data_df = data_df.dropna()

# Clean and preprocess text data
def preprocess_text(text):
    text = text.lower()  # Convert to lowercase
    text = ''.join(e for e in text if e.isalnum() or e.isspace())  # Remove special characters
    return text

data_df['text'] = data_df['text'].apply(preprocess_text)

# Encode labels
label_encoder = LabelEncoder()
data_df['label'] = label_encoder.fit_transform(data_df['label'])

"""**4. Tokenization**"""

tokenizer = XLNetTokenizer.from_pretrained('xlnet-base-cased')

def tokenize_data(examples):
    return tokenizer(examples['text'], padding='max_length', truncation=True, max_length=512)

# Split dataset into train and validation
train_df, val_df = train_test_split(data_df, test_size=0.2, random_state=42)

# Create Dataset objects
train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)

train_dataset = train_dataset.map(tokenize_data, batched=True)
val_dataset = val_dataset.map(tokenize_data, batched=True)

train_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])
val_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])

"""**5. Load the Model **"""

model = XLNetForSequenceClassification.from_pretrained('xlnet-base-cased', num_labels=2)

"""**6. Define Training Arguments**"""

# training_args = TrainingArguments(
#     output_dir='./results',
#     evaluation_strategy='epoch',
#     per_device_train_batch_size=8,
#     per_device_eval_batch_size=8,
#     learning_rate=2e-5,
#     num_train_epochs=5,
#     weight_decay=0.01
# )

import wandb
# Force wandb login to prompt for your API key
wandb.login()

from transformers import TrainingArguments, Trainer

"""
# Define training arguments for XLNet
training_args = TrainingArguments(
    output_dir="./results",                # Directory to save model checkpoints
    num_train_epochs=5,                    # Number of training epochs (adjust as needed)
    per_device_train_batch_size=8,         # Batch size for training
    per_device_eval_batch_size=8,          # Batch size for evaluation
    warmup_steps=500,                      # Warmup steps for learning rate scheduler
    weight_decay=0.01,                     # Regularization to prevent overfitting
    logging_dir="./logs",                  # Directory for storing logs
    logging_steps=100,                     # Log metrics every 100 steps
    eval_strategy="epoch",                 # Evaluate at the end of each epoch
    save_strategy="epoch",                 # Save the model at the end of each epoch
    load_best_model_at_end=True,           # Load the best model based on validation loss
    metric_for_best_model="eval_loss",     # Choose the best model based on validation loss
    greater_is_better=False,               # Lower validation loss is better
    report_to=["wandb"],                   # Enable wandb logging
    run_name="XLNet_Euphemism_Classification"  # Name for this wandb run
)
"""

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=10,  # Increase epochs
    per_device_train_batch_size=16,  # Increase batch size
    per_device_eval_batch_size=16,
    warmup_steps=1000,  # Increase warmup steps
    weight_decay=0.01,
    learning_rate=2e-5,  # Fine-tune learning rate
    logging_dir="./logs",
    logging_steps=50,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_f1",  # Track best model based on F1 score
    greater_is_better=True,
    report_to=["wandb"],
    run_name="XLNet_Euphemism_Tuning"
)

print("Training arguments successfully defined!")

"""7. Train the Model"""

# import numpy as np
# def compute_metrics(p):t
#     pred, labels = p
#     pred = np.argmax(pred, axis=1)
#     accuracy = accuracy_score(labels, pred)
#     precision = precision_score(labels, pred)
#     recall = recall_score(labels, pred)
#     f1 = f1_score(labels, pred)
#     return {'accuracy': accuracy, 'precision': precision, 'recall': recall, 'f1': f1}

# trainer = Trainer(
#     model=model,
#     args=training_args,
#     train_dataset=train_dataset,
#     eval_dataset=val_dataset,
#     compute_metrics=compute_metrics
# )

# trainer.train()

# Define the Trainer for XLNet
trainer = Trainer(
    model=model,                 # Your XLNet model (loaded via XLNetForSequenceClassification)
    args=training_args,          # Training arguments defined above
    train_dataset=train_dataset, # Your training dataset
    eval_dataset=val_dataset,    # Your validation dataset
    compute_metrics=None,        # No additional metrics (only loss will be tracked)
    tokenizer=tokenizer          # Your XLNet tokenizer (loaded via XLNetTokenizer)
)

# Train the model
trainer.train()

print("Training completed successfully!")

"""**8. Evaluate the Model**"""

eval_results = trainer.evaluate()
print(eval_results)

"""**10. Performance Metrics**"""

import numpy as np  # Make sure NumPy is imported
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Get predictions
predictions = trainer.predict(val_dataset)

# Convert logits to class predictions
preds = np.argmax(predictions.predictions, axis=1)

# True labels from validation dataset
true_labels = val_df['label']

# Compute Confusion Matrix and Classification Report
conf_matrix = confusion_matrix(true_labels, preds)
class_report = classification_report(true_labels, preds, target_names=["Non-Euphemism", "Euphemism"])

# Print the results
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{class_report}")

# Plot confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=["Non-Euphemism", "Euphemism"], yticklabels=["Non-Euphemism", "Euphemism"])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

"""**11. Save Trained Model **"""

# Define the path where you want to save the model
model_save_path = "/content/drive/MyDrive/Colab Notebooks/EuphemismClassification/XLNet_model"

# Save the model
model.save_pretrained(model_save_path)

# Save the tokenizer as well
tokenizer.save_pretrained(model_save_path)

print(f"Model and tokenizer saved successfully at: {model_save_path}")

"""**13. Test the Model**"""

import pandas as pd

# Load the test dataset
test_file_path = "/content/drive/MyDrive/Colab Notebooks/EuphemismClassification/FigLang_2024/EN_test.csv"
test_df = pd.read_csv(test_file_path)

# Preview the test dataset (optional)
print("Test Data Sample:")
print(test_df.head())

# Preprocess the text in the test dataset (use the same tokenizer as before)
test_encodings = tokenizer(test_df['text'].tolist(), truncation=True, padding=True, max_length=128)

# Create a PyTorch dataset for the test set
class TestDataset(torch.utils.data.Dataset):
    def __init__(self, encodings):
        self.encodings = encodings

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        return item

    def __len__(self):
        return len(self.encodings['input_ids'])

test_dataset = TestDataset(test_encodings)

# Make predictions on the test set
predictions, _, _ = trainer.predict(test_dataset)

# Convert logits to predicted labels (0 or 1)
test_preds = predictions.argmax(axis=-1)

# Create a new DataFrame with the test data and predicted labels
output_df = test_df[['Unnamed: 0', 'text']].copy()  # Use the correct column name for 'index'
output_df['predicted_label'] = test_preds

# Save the predictions to a new CSV file
output_file_path = "/content/drive/MyDrive/Colab Notebooks/EuphemismClassification/test_predictionsbyXLNET.csv"
output_df.to_csv(output_file_path, index=False)

# Inform the user
print(f"Test predictions saved successfully at {output_file_path}")

"""**14. Test Evaluation**"""

import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Load the reference (true) labels from the test reference file
reference_file_path = "/content/drive/MyDrive/Colab Notebooks/EuphemismClassification/FigLang_2024/EN_reference_test.csv"
reference_df = pd.read_csv(reference_file_path)

# Load the predicted labels from the previous output file
predicted_df = pd.read_csv(output_file_path)

# Ensure that the order of rows matches (if necessary)
# For this step, you can reset the index of both DataFrames if needed
# Reference and predicted labels should be in the same order
reference_labels = reference_df['label']
predicted_labels = predicted_df['predicted_label']

# Calculate the test accuracy
test_accuracy = accuracy_score(reference_labels, predicted_labels)
print(f"Test Accuracy: {test_accuracy:.4f}")

# Calculate the classification report
class_report = classification_report(reference_labels, predicted_labels)

# Print classification report
print("Classification Report:")
print(class_report)

"""**15. Generate Confusion Matrix**"""

# Generate the confusion matrix
conf_matrix = confusion_matrix(reference_labels, predicted_labels)

# Plot confusion matrix using seaborn
plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues", xticklabels=["Non-Euphemism", "Euphemism"], yticklabels=["Non-Euphemism", "Euphemism"])
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

"""**16. Save Model**"""

# Define the path where you want to save the model
model_save_path = "/content/drive/MyDrive/Colab Notebooks/EuphemismClassification/XL_Net_Euphemism_Model"

# Save the model
model.save_pretrained(model_save_path)

# Save the tokenizer as well
tokenizer.save_pretrained(model_save_path)

print(f"Model and tokenizer saved successfully at: {model_save_path}")

"""**17. Taking Input and generating output**"""

import pandas as pd
from transformers import XLNetTokenizer, XLNetForSequenceClassification
from torch.utils.data import DataLoader
from tqdm import tqdm
import torch
import os

# Load the trained model and tokenizer for XLNet
model_path = "/content/drive/MyDrive/Colab Notebooks/EuphemismClassification/XL_Net_Euphemism_Model"
model = XLNetForSequenceClassification.from_pretrained(model_path)
tokenizer = XLNetTokenizer.from_pretrained(model_path)

# Load the test data
def predict_labels(input_file_path):
    # Load the portion of the test dataset
    test_df = pd.read_csv(input_file_path)

    # Tokenize the text column (adjust max_length if needed)
    inputs = tokenizer(list(test_df['text']), padding=True, truncation=True, return_tensors="pt", max_length=512)

    # Put the model in evaluation mode
    model.eval()

    # Create a DataLoader for the test set
    test_loader = DataLoader(inputs['input_ids'], batch_size=16, shuffle=False)

    # List to store predictions
    predictions = []

    # Make predictions on the test set
    with torch.no_grad():
        for batch in tqdm(test_loader, desc="Predicting"):
            batch = batch.to(model.device)
            outputs = model(batch)
            logits = outputs.logits
            preds = torch.argmax(logits, dim=-1).cpu().numpy()
            predictions.extend(preds)

    # Create a new DataFrame with the original text and predicted labels
    output_df = test_df.copy()
    output_df['predicted_label'] = predictions

    # Create the output file path in the same folder with a new name 'labeledbyXLNet.csv'
    output_file_path = os.path.join(os.path.dirname(input_file_path), "labeledbyXLNet.csv")

    # Save the predictions to a new CSV file
    output_df.to_csv(output_file_path, index=False)

    print(f"Predictions saved to: {output_file_path}")

# Prompt for the file path of the portionoftestcorpus.csv
input_file_path = input("Please enter the path of the .csv file: ")

# Call the function to predict labels and save the output
predict_labels(input_file_path)